### ISSUE TITLE
Add setUint32, getInt32, setFloat32, getFloat32, setFloat64, getFloat64  functions

### ISSUE THREAD

**Issue by Gozala** [achingbrain/uint8arrays#1]
It appears that only reason protons library needs to allocate and pass around DataView objects along with Uint8Arrays is to use following methods:

- `setUint32`
- `getInt32`
- `setFloat32`
- `getFloat32`
- `setFloat64`
- `getFloat64`

It seem like it would be a good idea to expose them as static functions from these library so they could be used without having to deal with that in cases like this https://github.com/ipfs/protons/pull/14#issuecomment-668551817

**Comment by achingbrain** [comment]
The point there was that a lot of GC pressure would be created by creating new DataView objects repeatedly just to call one method.

How do you see that working here without creating short-lived objects?  Reimplementing these methods to set the values without using the convenience DataView class or similar?

**Comment by achingbrain** [comment]
Protons now uses `Uint8ArrayList` objects which have these methods defined so I don't think this is an issue any more.  Please reopen if so.
