### ISSUE TITLE
No type definitions in published version

### ISSUE THREAD

**Issue by alanshaw** [achingbrain/uint8arrays#12]
Looks like this project has type definitions https://github.com/achingbrain/uint8arrays/blob/master/package.json#L9 but none are available in the published version. Please can has?

**Comment by achingbrain** [comment]
That's weird, type defs are published in version `2.x.x` - e.g: https://unpkg.com/uint8arrays@2.0.5/dist/index.d.ts

What version are you using?

**Comment by alanshaw** [comment]
Ah yes, I have v1 installed.
