### ISSUE TITLE
Recent release broke our build

### ISSUE THREAD

**Issue by stbrody** [achingbrain/uint8arrays#17]
**Describe the bug**
All of a sudden today the build in our CI system started failing with the error:
```
 FAIL  src/__tests__/doc-state-subject.test.ts
  ● Test suite failed to run

    ReferenceError: TextDecoder is not defined

    > 1 | import CID from 'cids';
        | ^
      2 | import { DocStateSubject } from '../doc-state-subject';
      3 | import { CommitType, DocState } from "../doctype";
      4 | 

      at Object.<anonymous> (../../node_modules/uint8arrays/to-string.js:4:21)
      at Object.<anonymous> (../../node_modules/cids/node_modules/multihashes/src/index.js:9:28)
      at Object.<anonymous> (../../node_modules/cids/src/index.js:3:12)
      at Object.<anonymous> (src/__tests__/doc-state-subject.test.ts:1:1)
```

Note that I didn't manually update package.json in any way to get to the newest version, we just use the `^` and `~` in some places to pull in newer minor versions of packages when they get released, but minor versions aren't supposed to include breaking changes.  It seems like when uint8arrays v2.1.4 got released, npm picked it up and started using it in CI, which broke our build. Note our package.json specifies `"uint8arrays": "^2.0.5"`.

I'm currently in the process of going through all our package.json files and pinning to version `2.0.5` to get things working again, but ideally this wouldn't be necessary as the semantic versioning system should already protect us against pulling in unexpected breaking changes.

**Desktop (please complete the following information):**
 - OS: uname -a: `Linux Sonny 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

**Comment by stbrody** [comment]
Note this is likely related to https://github.com/multiformats/js-multibase/issues/90 as they started happening at the same time and look very similar

**Comment by achingbrain** [comment]
What js runtime is your CI using?

**Comment by achingbrain** [comment]
> ReferenceError: TextDecoder is not defined

TextDecoder is a global in all [modern browsers](https://caniuse.com/textencoder) and in node as of [v11](https://nodejs.org/api/globals.html#globals_textdecoder) - are you using an older environment?

**Comment by stbrody** [comment]
> > ReferenceError: TextDecoder is not defined
> 
> TextDecoder is a global in all [modern browsers](https://caniuse.com/textencoder) and in node as of [v11](https://nodejs.org/api/globals.html#globals_textdecoder) - are you using an older environment?

We use node v14 for everything

**Comment by stbrody** [comment]
I can repro this on my local machine as well, where I have
```
> node --version
v14.15.5
```

**Comment by achingbrain** [comment]
Looks like Jest might have an incomplete environment? https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test

**Comment by stbrody** [comment]
> Looks like Jest might have an incomplete environment? [stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test](https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test)

Yeah, that does seem likely to be the issue.  Instead of having to update all of our packages that depend in any way on uint8arrays or multibase, would you be open to a PR that changes the use of `TextEncoder` within those packages to import `util` and use `util.TextEncoder` @achingbrain?

**Comment by achingbrain** [comment]
It shouldn’t be necessary to use node internals to use TextEncoder/Decoder as it’s defined globally in supported environments. We’re also trying to remove use of node internals wherever possible so I’d rather not unless it’s impossible to do it any other way.

Really JSDom needs to add global TextEncoder/Decoder implementations: https://github.com/jsdom/jsdom/issues/2524

**Comment by achingbrain** [comment]
It looks like there’s an in-progress PR to do exactly that: https://github.com/jsdom/whatwg-encoding/pull/11

**Comment by stbrody** [comment]
Sorry about my panic and frustration-fueled issue reporting yesterday, I was really shaken by our whole build breaking out from under us with no changes from our end.  Thank you for all your help and for pointing me in the right direction!  We were able to fix the issue by tweaking our jest configuration.

Closing this issue as there is nothing needed within `uint8arrays`

**Comment by achingbrain** [comment]
Not at all, I’m sorry you had a rough time. Glad you got to the bottom of it - hopefully that JSDom pr will get merged & rolled up soon.
