### ISSUE TITLE
React-Native Support

### ISSUE THREAD

**Issue by pedrouid** [achingbrain/uint8arrays#37]
Independent of the React-Native version, we have observed incompatibility with both JSC and Hermes runtimes. The issue stems from errors caused by TextEncoder being undefined. 

I would like to propose that we would create a polyfill as described here: https://github.com/WalletConnect/walletconnect-monorepo/issues/1338#issuecomment-1210995006

Available separately for react-native through a target so it's not used in browser or node.js environments

**Comment by theblockstalk** [comment]
Why doesn't the `package.json` define a require export e.g.
```json
{
  "exports": {
    ".": {
      "types": "./build/types/index.d.ts",
      "require": "./build/index.cjs", ### this is missing
      "import": "./build/index.module.js"
    }
  },
}
```
this is used by default in nodejs bundlers, also in the jest default bundler and the expo (react native) default bundler. We keep getting issues with this that prevent us from using uint8arrays in react native

**Comment by tangzijun** [comment]
+ 1  This need is very urgent

**Comment by tangzijun** [comment]
+1 This need is very urgent

**Comment by achingbrain** [comment]
This module works with react-native/expo - I put [this demo app together recently](https://github.com/ipfs-shipyard/js-libp2p-react-native) that uses this module internally.

It all works, you just have to [turn on](https://github.com/ipfs-shipyard/js-libp2p-react-native/blob/main/metro.config.js#L3) the experimental [package exports support](https://reactnative.dev/blog/2023/06/21/package-exports-support).
