### ISSUE TITLE
Breaking change in minor version 3.1.0

### ISSUE THREAD

**Issue by dholms** [achingbrain/uint8arrays#38]
Hey there, I wanted to point out that minor version 3.1.0 included breaking changes. 

Specifically: "If globalThis.Buffer is defined, it will be used in preference to globalThis.Uint8Array."

Our code is standardized around Uint8Arrays. This is important for apis such as Webcrypto which expect `Uint8Arrays` or `ArrayBuffer`s and don't work correctly on Node buffers. 

I think this is a misleading change as this is a `uint8arrays` library not a `BufferLike` library. Concatenating two `Uint8Arrays` and receiving a `Buffer` back breaks developer expectations.

However, if this change does stick around, I would encourage a major version bump.

**Comment by achingbrain** [comment]
The node `Buffer` class extends `Uint8Array` so the interface contract is maintained hence there was no major version bump.  `Uint8Array`s are also [slower to initialise](https://github.com/paulmillr/noble-ed25519/issues/45#issuecomment-1016449023) and [less memory efficient](https://github.com/ChainSafe/ssz/blob/master/packages/ssz/test/memory/bytes.test.ts) than node `Buffer`s.

> This is important for apis such as Webcrypto which expect Uint8Arrays or ArrayBuffers and don't work correctly on Node buffers.

Can you share a simple example of it not working correctly please?

**Comment by dholms** [comment]
sure thing, here's one I put together:
```js
import * as uint8arrays from 'uint8arrays'
import { webcrypto } from 'crypto'

const toSign = uint8arrays.fromString('sign me', 'utf-8')

const keypair = await webcrypto.subtle.generateKey(
  { name: 'ECDSA', namedCurve: 'P-256' },
  true,
  ['sign', 'verify'],
)

const sig = await webcrypto.subtle.sign(
  { name: 'ECDSA', hash: { name: 'SHA-256' } },
  keypair.privateKey,
  toSign.buffer,
)

const toVerify = uint8arrays.fromString(uint8arrays.toString(toSign, 'utf-8'), 'utf-8')
const isValid = await webcrypto.subtle.verify(
  { name: 'ECDSA', hash: { name: 'SHA-256' } },
  keypair.publicKey,
  sig,
  toVerify.buffer,
)

console.log("Is Valid: ", isValid)
```

This return true on version 3.0.0 and false on 3.1.0.

**Comment by achingbrain** [comment]
The problem here is you are passing the underlying `ArrayBuffer` into `webcrypto.subtle.sign` and `webcrypto.subtle.verify` without reference to any potential [.byteOffeset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteOffset) or [.byteLength](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteLength).

MDN [says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/buffer):

> Because a typed array is a view of a buffer, the underlying buffer may be longer than the typed array itself.

It's dangerous to assume they are not because you even if you had no references to node `Buffer`s anywhere you could have been passed the output from `.subarray`:

```js
const buf = new TextEncoder().encode('sign me please')
const sub = arr.subarray(0, 7)

console.info(new TextDecoder().decode(buf)) // sign me
console.info(sub.byteLength) // 7
console.info(sub.buffer.byteLength) // 14
```

If you instead pass `toSign` and `toVerify` in, it will print `true`.

I think we should still merge #39 as `Buffer`s are not 100% compatible with `Uint8Array`s (see [Buffer.slice](https://nodejs.org/api/buffer.html#bufslicestart-end)) but your code above will still print `false` due to it ignoring the `.byteOffset` and `.byteLength` values.

**Comment by achingbrain** [comment]
@hugomrdias are you seeing the same issue or something different?

**Comment by dholms** [comment]
Thank you for the feedback on that. I believe that WebCrypto used to require ArrayBuffers but has since updated to allow TypedArrays. I've updated our code to pass in the Uint8Array instead of the underlying ArrayBuffer 👍

**Comment by hugomrdias** [comment]
39 fixes my issues so all good

**Comment by nazarhussain** [comment]
Same issue for me. It's introduced in following PR https://github.com/achingbrain/uint8arrays/pull/36. The function `fromString` should not return any type other than `Uint8Array`.

**Comment by achingbrain** [comment]
@nazarhussain node `Buffer`s are `Uint8Array`s:

```console
% node
Welcome to Node.js v16.13.0.
Type ".help" for more information.
> Buffer.from([]) instanceof Uint8Array
true
```

Can you please share a bit more about the issue you are seeing?  What is the error message and how do I replicate it?

**Comment by nazarhussain** [comment]
@achingbrain Yes I agree to you to the level of the nodejs environment. But I believe the extended ecosystem is not yet ready. `Uint8Array` and `Buffer` are treated as different types. 

Check this script live at https://runkit.com/nazarhussain/6332f59483f5b70008db9d8f For reference. 

```js
const sinon = require("sinon"); 
const assert = require("assert"); 

var object = {
  test(input) {
    // console.log(input);
  },
};

var spy = sinon.spy(object, "test");

object.test("String"); 
assert(spy.calledWith("String"));
spy.resetHistory();

object.test(Buffer.from([1]))
assert(spy.calledWith(Buffer.from([1])));
spy.resetHistory();

object.test(new Uint8Array([1]))
assert(spy.calledWith(new Uint8Array([1])));
spy.resetHistory();

object.test(Buffer.from([1]))
assert(spy.calledWith(new Uint8Array([1])), "Uint8Array is not considered as Buffer");
spy.resetHistory();
```

**Comment by achingbrain** [comment]
> Uint8Array and Buffer are treated as different types.

This is because they are different types - sinon's matchers fail because the class name of `Uint8Array` and `Buffer` are different, which is completely expected.

In your test I think you're trying to assert that the contents of the arguments was the same, in which case you should compare the contents of the arguments:

```js
const { equals } = require('uint8arrays/equals')

assert(equals(spy.getCall(0).args[0], new Uint8Array([1]), "Not equal"));
```

**Comment by nazarhussain** [comment]
I believe you explained it yourself. 

> This is because they are different types

I am just stating as these are different types and can cause trouble across different projects in the eco-system, so should be considered as a breaking change. e.g. I updated the package and a ton of my test using sinon `.calledWith` starts failing and in most of the cases it's very tedious to use `uint8arrays/equals`. As sinon is a widely used framework, consider how many projects could affect by this change.

**Comment by achingbrain** [comment]
They have different class names so they are different types in the way that `Object` and `Number` are different types.
