### ISSUE TITLE
Open to use conditional exports instead of globalThis.Buffer?

### ISSUE THREAD

**Issue by ukstv** [achingbrain/uint8arrays#87]
Hey, @achingbrain recently it was discovered that some crypto wallets forcefully polypill `globalThis.Buffer` with some garbage Buffer implementations. `uint8arrays` uses `globalThis.Buffer` quite extensively. I guess, the intent is to use native Node.js Buffer, not some polyfill. How do you think about moving `Buffer`-related code behind conditional exports?

Say, you could have `#alloc` which resolves to `./buffer-alloc.js` when `node`-imported, and `./uint8array-alloc.js` by default.

Also, node.js Buffer could be found in `node:buffer` on Bun and Node.js, which makes the code a bit simpler to read, and it definitely avoids implications of globalThis pollution.

**Comment by achingbrain** [comment]
> it was discovered that some crypto wallets forcefully polypill globalThis.Buffer with some garbage Buffer implementations

For my own education do you have some links for this?

Yes, though, I am open to doing this in a better way.  A few points:

1. It uses `globalThis.Buffer` instead of importing from `node:buffer` to avoid needing extra config for bundlers
2. Conditional exports work when consuming this module but they don't override relative imports from within the module

It might just need the `node:buffer` stuff putting in it's own file and a `"browser"` field override in the `package.json` file for it after all.

**Comment by ukstv** [comment]
> For my own education do you have some links for this?

Plug wallet for ICP https://plugwallet.ooo injects globalThis.Buffer Apparently, it is quite popular. Has 100,000 users according to Google Chrome Web Store: https://chromewebstore.google.com/detail/plug/cfbfdhimifdmdehjmkdobpcjfefblkjm

> Yes, though, I am open to doing this in a better way

Whatever you prefer!

> Conditional exports work when consuming this module but they don't override relative imports from within the module

My bad, was not precise enough. I thought about [Subpath Imports](https://nodejs.org/docs/latest/api/packages.html#subpath-imports), which seem to be supported all right by bundlers.

**Comment by ukstv** [comment]
To confirm on your own:
1. Install Plug wallet on Chrome.
2. Open dev console on any page
3. Type `globalThis.Buffer` => apparently, it is there.

**Comment by ukstv** [comment]
@achingbrain Any news? Are you open to help from my end?

**Comment by achingbrain** [comment]
Hey, yes - please open a PR with the proposed changes and we can discuss there.

**Comment by ukstv** [comment]
Great!

**Comment by ukstv** [comment]
@oed Just FYI, so that you are in the loop here.

**Comment by ukstv** [comment]
@achingbrain Please, could you have a look at the PR for moving out of globalThis.Buffer?

**Comment by ukstv** [comment]
Yahoo!!!
